project_name: waechter
before:
  hooks:
    - go mod tidy
builds:
  - env:
    - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    main: ./cmd/waechter
archives:
  - files:
    - locales/*
    - LICENSE
checksum:
  name_template: 'checksums.txt'

dockers:
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "mtrossbach/{{ .ProjectName }}:{{ .Version }}-arm64"
    extra_files:
      - locales
      - LICENSE
  - use: buildx
    goos: linux
    goarch: arm
    goarm: 6
    image_templates:
      - "mtrossbach/{{ .ProjectName }}:{{ .Version }}-armv6"
    extra_files:
      - locales
      - LICENSE
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "mtrossbach/{{ .ProjectName }}:{{ .Version }}-amd64"
    extra_files:
      - locales
      - LICENSE
      
docker_manifests:
  - name_template: "mtrossbach/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "mtrossbach/{{ .ProjectName }}:{{ .Version }}-arm64"
      - "mtrossbach/{{ .ProjectName }}:{{ .Version }}-armv6"
      - "mtrossbach/{{ .ProjectName }}:{{ .Version }}-amd64"
  - name_template: "mtrossbach/{{ .ProjectName }}:latest"
    image_templates:
      - "mtrossbach/{{ .ProjectName }}:{{ .Version }}-arm64"
      - "mtrossbach/{{ .ProjectName }}:{{ .Version }}-armv6"
      - "mtrossbach/{{ .ProjectName }}:{{ .Version }}-amd64"     
    
release:
  github:
    owner: mtrossbach
    name: waechter
  draft: true
